language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup > /dev/null'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish > /dev/null'

env:
  global:
    - secure: |-
        CtCYjJfYm+OR85PX9Ey/ICYje/mNycbrXR+CV1F2UfXWlgVUb0qSu0LDlYQb
        TUwCnW/ljMb2uH32E2W/0W6/I9QEb8WkoPEhsKwArfAKvJPh+MCko1QkeDpu
        g5bXzRyTlms5dBrOFMKT7KaTF6W4EvdevBDAS51nY/jYySpStPk=
    - secure: |-
        UoBRLTGs6aydk4jHitA48BQnhZ8r1Gb77JKitMUgJAZ3HjgpllqhpyB0CP23
        OoXHgywjQ0Jmn3dbXC7V59YwOWgfo87K/FuRUhGXm5/8G3YXPGlDBxV7XTD4
        n1Q2OIOTZAfIdrT0R1b3GGscyqJCXDcmdbbv46I/SjxYYTzo07I=
    - secure: |-
        biv21AnivzW1Kde0+ae9SZ1ykQWNeZ9ek1uZomK+YEEqojNybCKCzgoGn5Sf
        l4sZG+uQ//aYlf+vQSQBi1KsOPBOk2d5XMWXRZ6aWXGqlGg5nX6u8BYDkMTJ
        hCIpzmNPlvzH2w53hi1dXcTEsmJ3lixaeRC9p1yq0Yx6YqA/zfc=
    - secure: |-
        E3vGDCIZgK+Cl8LTV21m3ZtEOzGtUOlSv6OFUMeOJyHI6uX5XtEaCKLX0Wba
        c2hQyZMIDcktUs9ou6uXSH+vs6mvQxIQr2gC7NQMfqR11V5V7+aTME5q7uZ4
        +Tt2cySe6KUDb2U0HyTNmzDd5WG3CoBFbpdgin5aoTyTFHGeXHE=
    - secure: |-
        fNmdiG50AgwqkiQ5u1jdqSOnMZJLUzV4wUKuTWBQysevqaxgg1RaIvaO6q9+
        ZMg6qO8Oc3TqxLniSfGOJuzD94cQrYqyYnkhliyBvZtEYZusoO9rVmVicNf4
        NHG3tum5uslAYGVRFJ8yqwdm+XLDAXJnNflBiA3sU2Lj1zatkzo=
